name: CI
on: [push, pull_request]

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            triple: x86_64-linux-musl
            name: linux_x64
          - os: windows
            triple: x86_64-w64-mingw32
            name: windows_x64
        include:
          - target:
              os: linux
            builder: ubuntu-20.04
    defaults:
      run:
        shell: bash

    name: '${{ matrix.name }}'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch nimble
        run: |
          wget https://github.com/nim-lang/nimble/releases/download/latest/nimble-${{matrix.target.name}}.tar.gz
          tar xvf nimble-${{matrix.target.name}}.tar.gz
          echo "$PWD" >> $GITHUB_PATH

      - name: Build nph
        run: |
            nimble setup -l
            nimble build

      - name: Check formatting
        run: |
          find -name "*.nim"  ! -path "./tests/before/*" ! -path "./nimbledeps/*" -print0 | xargs -0 -n1 ./nph
          git diff
          # find -name "*.nim"  ! -path "./tests/before/*" ! -path "./nimbledeps/*" -print0 | xargs -0 -n1 ./nph --check
