name: CI
on: [push, pull_request]

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            triple: x86_64-linux-musl
            name: linux_x64
          - os: macosx
            triple: x86_64-apple-darwin14
            name: macosx_x64
          - os: windows
            triple: x86_64-w64-mingw32
            name: windows_x64
        include:
          - target:
              os: linux
            builder: ubuntu-20.04
          - target:
              os: macosx
            builder: macos-12
          - target:
              os: windows
            builder: windows-2019
    defaults:
      run:
        shell: bash

    name: CI '${{ matrix.target.name }}'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v4

      - uses: nim-lang/setup-nimble-action@v1
        with:
          nimble-version: '0.16.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nph
        run: |
           nimble build

      - name: Check formatting
        run: |
          ! ./nph --check tests/before
          ./nph --check tests/after

          ./nph src
          git diff --exit-code

